### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by edsinkevic** [Lameguy64/PSn00bSDK#42]
So basically I've ran these commands:
cmake -S . -B ./build -G Ninja --install-prefix ~/disobin/psx/sdk
and then..
cmake --build ./build
... everything is alright up to this moment

[15/16] Building CXX object CMakeFiles/smxlink.dir/smxlink/main.cpp.o
[16/16] Linking CXX executable smxlink
[24/40] Performing download step (git clone) for 'mkpsxiso'
FAILED: mkpsxiso-prefix/src/mkpsxiso-stamp/mkpsxiso-download /home/edvin/Downloads/PSn00bSDK/build/mkpsxiso-prefix/src/mkpsxiso-stamp/mkpsxiso-download
cd /home/edvin/Downloads/PSn00bSDK/build/mkpsxiso-prefix/src && /usr/bin/cmake -P /home/edvin/Downloads/PSn00bSDK/build/mkpsxiso-prefix/tmp/mkpsxiso-gitclone.cmake && /usr/bin/cmake -E touch /home/edvin/Downloads/PSn00bSDK/build/mkpsxiso-prefix/src/mkpsxiso-stamp/mkpsxiso-download
Cloning into 'mkpsxiso'...
fatal: invalid reference: cmake
CMake Error at /home/edvin/Downloads/PSn00bSDK/build/mkpsxiso-prefix/tmp/mkpsxiso-gitclone.cmake:40 (message):
  Failed to checkout tag: 'cmake'

[25/40] Performing install step for 'tools'
[0/1] Install the project...
-- Install configuration: ""
-- Installing: /home/edvin/Downloads/PSn00bSDK/build/install_tree/bin/elf2x
-- Installing: /home/edvin/Downloads/PSn00bSDK/build/install_tree/bin/elf2cpe
-- Installing: /home/edvin/Downloads/PSn00bSDK/build/install_tree/bin/smxlink
-- Installing: /home/edvin/Downloads/PSn00bSDK/build/install_tree/bin/lzpack
-- Installing: /home/edvin/Downloads/PSn00bSDK/build/install_tree/share/psn00bsdk/plugin
-- Installing: /home/edvin/Downloads/PSn00bSDK/build/install_tree/share/psn00bsdk/plugin/io_export_smx_v3.py
ninja: build stopped: subcommand failed.

**Comment by alex-free** [comment]
> Unsurprisingly it's yet another issue with the dynamic linker (another creation of mine) and the `dynlink` example.
> 
> I actually did some tests right now and it looks like older GCC versions, including 7.4.0, can't properly build MIPS DLLs in the non-standard format expected by my dynamic linker. I don't know what actually causes `_procedure_table_size` to be undefined but it's probably some obscure MIPS ABI stuff, or maybe a GCC bug that got fixed in later releases. I'm going to remove the recommendation to use GCC 7.4.0 from the toolchain guide.
> 
> Try building binutils 2.37 and GCC 11.2.0, which should work (although [you may have to do some small modifications](/spicyjpeg/PSn00bSDK/blob/cmake/TOOLCHAIN.md#building-binutils) to the binutils sources). I know compiling the toolchain a tedious process, but I just tried rebuilding the SDK and examples using GCC 11.2.0 on an Ubuntu VM and I had no issues.

This change fixed building on Debian 11 (without modifications to either binutils or gcc), I have successfully updated https://alex-free.github.io/psn00bsdk_installer/ for the CMake based toolchain.

**Comment by spicyjpeg** [comment]
@alex-free: I took a quick look at your installer script. I have a few suggestions:

- You can safely remove the linker script patching step as the SDK has shipped its own ldscripts for a while now.
- You might want to build binutils and GCC for `mipsel-none-elf` (instead of `mipsel-unknown-elf`) and pass `-DPSN00BSDK_TARGET=mipsel-none-elf` to CMake for future proofing, as I have switched to `mipsel-none-elf` as the default toolchain in my [work-in-progress fork](/spicyjpeg/PSn00bSDK/tree/actions) (updated installation instructions [here](/spicyjpeg/PSn00bSDK/blob/actions/doc/installation.md)). The same branch has GitHub Actions CI scripts and support for building installer packages as well by the way.
- It's better to install both the SDK and the toolchain to `/usr/local` rather than `/usr/local/mipsel-unknown-elf`, for consistency with the way the toolchain is bundled in the packages generated by the CI script. CMake's default installation prefix is already `/usr/local`, however you might still want to provide an option to change it.
- Another suggestion would be to install a `create_psn00bsdk_project` or similar script to quickly generate a new project. The script would copy the contents of the `/usr/local/share/psn00bsdk/template` directory and populate the `CMakePresets.json` file (see [here](/spicyjpeg/PSn00bSDK/blob/actions/doc/cmake_reference.md#setup)) with the paths that were chosen during installation.
