### ISSUE TITLE
antivirus flags as unsafe

### ISSUE THREAD

**Issue by Pacsonic** [Lameguy64/PSn00bSDK#52]
My antivirus flags every single file in the build unsafe and deletes them. Is there a way to make sure this doesn't happen?

**Comment by spicyjpeg** [comment]
You should not keep your antivirus enabled while compiling your projects, or at least you should exclude your project and build directories from real-time scanning. This will not only prevent issues with false positives but will also greatly speed up the build process, since the behavior of most compilers tends to trip the detection hooks installed by your antivirus software. This applies to any programming language and platform, not just to C/C++ with PSn00bSDK.

**Comment by Pacsonic** [comment]
It's when I download them off the web.

**Comment by spicyjpeg** [comment]
There is nothing we can do to prevent antivirus software from treating PSn00bSDK's binaries as if they were malware (short of signing them which would be ridiculously expensive), so I'm going to close this issue. The SDK is known to work on fresh Windows installations; setting up a Linux VM is also an option if you don't want to change your AV's settings.
