### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by KoopintheHub** [Lameguy64/PSn00bSDK#53]
When I compile the template I get a weird message in CMake.
Here's the log:
```
Preset CMake variables:

  CMAKE_BUILD_TYPE="Debug"
  CMAKE_TOOLCHAIN_FILE="C:\PSn00bSDK\lib\libpsn00b/cmake/sdk.cmake"
  PSN00BSDK_TARGET="mipsel-none-elf"
  PSN00BSDK_TC=""

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/d/template/build/CMakeFiles/CMakeOutput.log".

```
It seems it can't find the program names "Ninja". Do I need to install something or am I doing something wrong?

**Comment by spicyjpeg** [comment]
The default presets assume you have [Ninja](https://ninja-build.org/) installed (it is a single self-contained executable you can just drop into any directory listed in your `PATH` environment variable). You can use CMake's `-G` option or edit the presets to use MSys2 or MinGW `make` instead, although using Ninja is recommended since it's faster and easier to get running on Windows compared to `make`.

Ninja will be bundled in the next PSn00bSDK release by the way, so this is just a temporary issue.

**Comment by spicyjpeg** [comment]
I'm closing this issue since Ninja has been bundled with PSn00bSDK binary releases starting from v0.20, so there should (hopefully) be no issues now.
