### ISSUE TITLE
not able to compile a simple test program

### ISSUE THREAD

**Issue by stephkno** [Lameguy64/PSn00bSDK#58]
mipsel-none-elf-gcc is not accepting -EL as an option when trying to build CMakeTmp/testCCompiler.c. `unrecognized option '-EL'`. Also getting warning that the target architecture is unknown.

**Comment by spicyjpeg** [comment]
I was not able to replicate this (and my CMake scripts do not pass `-EL` to the compiler explicitly, so I'm not sure about what is going on).

Could you provide more details on how you installed the SDK and which version of the toolchain you are using? You can invoke `mipsel-none-elf-gcc --version` and `mipsel-none-elf-as --version` to retrieve the version of GCC and binutils, respectively. If you can also post the full output of CMake up until the error (make sure you delete the build directory to force a full rebuild) I can look into it and see if there is any obvious bug or mistake that might have triggered it.

**Comment by stephkno** [comment]
Nevermind, I was just installing incorrectly. I set the wrong directory for PSN00BSDK_LIBS and my attempts to fix the cmake errors resulted in this bug.

**Comment by spicyjpeg** [comment]
I'm glad you were able to figure it out. By the way, if you compiled the SDK from source rather than using the prebuilt 0.19 package, beware that there currently is a bug in the interrupt handling code that results in dropped IRQs and all kinds of consequences (most importantly failures when attempting to read files from the CD). I'm going to open a PR tomorrow to fix this, after which you'll be able to rebuild or otherwise update to version 0.21.
