### ISSUE TITLE
error: Unknown CMake command "psn00bsdk_add_executable"

### ISSUE THREAD

**Issue by N3koSempai** [Lameguy64/PSn00bSDK#73]
I have this error when try make in my project for first time.

`
CMake Error at CMakeLists.txt:14 (psn00bsdk_add_executable):
  Unknown CMake command "psn00bsdk_add_executable"
`

**Comment by spicyjpeg** [comment]
Looks like you did not set the path to the toolchain file correctly. This can happen for several reasons:

- you are using the default `CMakePresets.json` file and passing `--preset default` to CMake, but did not set the `PSN00BSDK_LIBS` environment variable or made a typo in it;
- you edited `CMakePresets.json` to add the path to your PSn00bSDK installation to it, but made a mistake (e.g. using backslashes instead of forward slashes, which won't work since backslashes in JSON strings are escape characters);
- you are not using CMake presets at all. In that case you will have to pass `-DCMAKE_TOOLCHAIN_FILE=/path/to/lib/libpsn00b/cmake/sdk.cmake` to CMake when configuring your project.

Double check your environment variables and make sure they are set correctly (the `set` command on Windows or `env` on Linux/macOS will print the values of all environment variables). You may have to close and reopen your terminal window, or sometimes reboot, for changes made to environment variables to apply.

**Comment by N3koSempai** [comment]
The problem has been solved.

It was my mistake. When I followed the tutorial on the web it only says use ("make") when I should have followed the create a project section of this github repository. Everything worked correctly.
