### ISSUE TITLE
Batch STR conversion utility

### ISSUE THREAD

**Issue by wizzomafizzo** [Lameguy64/PSn00bSDK#74]
Hi. I was wondering if a utility exists that could convert a video file to a STR file from the command line? Preferably in Linux but through wine would be ok too.

I've checked through your old posts about this and several other tools, they all seem to point back to MC32 as the final step, which appears to only let you convert through a GUI (and only Windows).

I might be interested in creating such a tool myself if nothing exists, but wanted to check here first. Especially if there's some good documentation on the format.

**Comment by spicyjpeg** [comment]
[Here you go.](https://github.com/WonderfulToolchain/psxavenc)

Sorry for the late reply (been busy with other things) but I did contribute to this command-line audio and video conversion tool a while ago. You will have to build it yourself, but it works on any OS and only requires FFmpeg as a dependency. It can ingest video files in any format and resolution, unlike Sony's ancient tool which requires a whole intermediate transcoding step. The only "real" limitation is that it does not yet support v3 bitstreams so you are limited to v2, but that shouldn't be much of an issue since there isn't a significant quality difference between the two anyway.

Note that there seems to be a bug with colorspace conversion in the main branch that results in completely black videos being generated; in the meantime you can use my [colorspace-fix branch](https://github.com/spicyjpeg/psxavenc/tree/colorspace-fix), which seems to be functional.

**Comment by wizzomafizzo** [comment]
Wow! That's perfect. Thank you very much!!
